added Dto models, BookController, missing methods in repository and service
maxymmusiienko/BookShop pull request #2
Opened 2023-12-12 10:51 UTC by maxymmusiienko

2023-12-12 16:25 UTC, okuzan requested changes

2023-12-12 16:25 UTC, okuzan commented on src/main/java/com/example/bookshop/dto/BookDto.java
> +    private String coverImage;
remove empty lines between the fields

2023-12-12 16:25 UTC, okuzan commented on src/main/java/com/example/bookshop/dto/BookDto.java
> +
use lombok annotations instead, like @Data

2023-12-12 16:25 UTC, okuzan commented on src/main/java/com/example/bookshop/model/Book.java
> +                + "} ";
takes too much space

2023-12-12 16:25 UTC, okuzan commented on src/main/java/com/example/bookshop/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Error while getting all users", e);
```suggestion
            throw new RuntimeException("Error while getting all the books", e);
```

2023-12-14 11:50 UTC, kozhukhovsky approved these changes

2023-12-18 10:10 UTC, closed without merging