added JWT validation, /login endpoint
maxymmusiienko/BookShop pull request #7
Opened 2023-12-27 15:03 UTC by maxymmusiienko

2023-12-28 11:40 UTC, Sanderfuck requested changes

2023-12-28 11:40 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/dto/UserLoginRequestDto.java
> +    @Length(min = 8, max = 25)
Can we use without @NotBlank annotation?

2023-12-28 11:40 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/service/AuthenticationServiceImpl.java
> +
```suggestion
```

2023-12-28 11:40 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/service/AuthenticationServiceImpl.java
> +    private JwtUtil jwtUtil;
Try to inject by constructor and you can use @requiredArgsConstructor of lombok for this but fields should be final

2023-12-28 11:40 UTC, Sanderfuck commented on src/test/resources/application.properties
> +jwt.expiration=6000000000000000
In test you don`t need real duration

2023-12-28 11:40 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/controller/AuthenticationController.java
```suggestion
```

2023-12-28 18:55 UTC, olekskov approved these changes

2023-12-30 17:04 UTC, Ivan95kos approved these changes
Great job

2023-12-30 21:54 UTC, merged